# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'WTXMMicroblog' do
pod 'AFNetworking', '~> 2.6.0'
pod 'pop', '~> 1.0.7'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJExtension', '~> 2.5.9'
end

target 'WTXMMicroblogTests' do
pod 'AFNetworking', '~> 2.6.0'
pod 'pop', '~> 1.0.7'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJExtension', '~> 2.5.9'
end

